version: '3.9'

services:

  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      #      - pgdata:/var/lib/postgresql/data
      - ./modules-data.sql:/docker-entrypoint-initdb.d/modules-data.sql

  studentportalapp:

    build:
      dockerfile: Dockerfile

    ports:
      - "8080:8080"

    depends_on:
      - db