// This TypeScript modules definition file is generated by vaadin-maven-plugin.
// You can not directly import your different static files into TypeScript,
// This is needed for TypeScript compiler to declare and export as a TypeScript module.
// It is recommended to commit this file to the VCS.
// You might want to change the configurations to fit your preferences
declare module '*.module.css' {
    declare const styles: Record<string, string>;
    export default styles;
}
declare module '*.module.sass' {
    declare const styles: Record<string, string>;
    export default styles;
}
declare module '*.module.scss' {
    declare const styles: Record<string, string>;
    export default styles;
}
declare module '*.module.less' {
    declare const classes: Record<string, string>;
    export default classes;
}
declare module '*.module.styl' {
    declare const classes: Record<string, string>;
    export default classes;
}

/* CSS FILES */
declare module '*.css';
declare module '*.sass';
declare module '*.scss';
declare module '*.less';
declare module '*.styl';

/* IMAGES */
declare module '*.svg' {
    const ref: string;
    export default ref;
}
declare module '*.bmp' {
    const ref: string;
    export default ref;
}
declare module '*.gif' {
    const ref: string;
    export default ref;
}
declare module '*.jpg' {
    const ref: string;
    export default ref;
}
declare module '*.jpeg' {
    const ref: string;
    export default ref;
}
declare module '*.png' {
    const ref: string;
    export default ref;
}
declare module '*.avif' {
    const ref: string;
    export default ref;
}
declare module '*.webp' {
    const ref: string;
    export default ref;
}

