server:
  port: 8666

eureka:
  client:
    service-url:
      defaultZone: http://discoveryserver:8761/eureka

spring:
  ## Application Configurations ##
  application:
    name: apiGateway

  ## Cloud Configurations ##
  cloud:
    gateway:
      mvc:
        routes: # Routes configuration

          # Discovery Server #
          - id: discoveryServer
            uri: http://discoveryserver:8761
            predicates:
              - Path=/eureka/web
            filters:
              - SetPath=/

            # Discovery Server static resources#
          - id: discoveryServer-static
            uri: http://discoveryserver:8761
            predicates:
              - Path=/eureka/**

            # Library App #
          - id: libraryapp
            #            uri: lb://library-service
            uri: http://libraryapp:8082
            predicates:
              - Path=/library/**
            filters:
              - SetPath=/

          # Finance App #
          - id: libraryapp
            #            uri: lb://finance
            uri: http://finance:8081
            predicates:
              - Path=/finance/**
            filters:
              - SetPath=/


## Debugging Configurations ##
logging:
  level:
    root: INFO
    org.springframework.cloud.route.RouteDefinitionLocator: INFO
    org.springframework.cloud.gateway: TRACE

